#!/usr/bin/expect -f
#
# rpmsign-batch.expect : expect powered rpm signing command
#

proc usage {} {
        send_user "Usage: rpm-sign passphrase rpmfile\n\n"
        exit
}

if {[llength $argv]!=2} usage

set passphrase [lindex $argv 0]
set rpmfile [lindex $argv 1]

spawn rpmsign --resign $rpmfile
expect -exact "Passphrase: "
send -- "$passphrase\r"
expect eof
